### ISSUE TITLE
Use Github's list based markdown

### ISSUE THREAD

**Issue by ashwanthkumar** [salaikumar/Todo-List#1]
You could use Github's special markdown syntax for your TODO list, like
- [x] Write a simple Dropwizard service
- [ ] Test it on an EC2 instance 
- [ ] Benchmark the service

The code I used in this issue is

```
- [x] Write a simple Dropwizard service
- [ ] Test it on an EC2 instance 
- [ ] Benchmark the service
```

**Comment by salaikumar** [comment]
Sure. Will update it. Thanks. :).
